# The URL the site will be built for
base_url = "https://justazes.github.io/JessICan/"
generate_rss = true
compile_sass = true

title = "JessICan - natürlich!"
description = "Willkommen auf JessICan - natürlich!"
highlight_code = true

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Jessi"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Start"},
    {url = "$BASE_URL/blog", name = "Blog"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "https://twitter.com", icon="fab fa-instagram"}
]
