# The URL the site will be built for
base_url = "https://tierheilpraxis-jessican.de"
generate_rss = false
compile_sass = true
default_language = "de"
minify_html = true
title = "Tierheilpraxis JessICan"
description = "Tierheilpraktiker JessICan: Akupunktur, Homöopathie, Phytotherapie, Manuelle Therapie, Aromatherapie & Ernährungsberatung für Hund & Pferd"
taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Jessi von JessICan"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Startseite"},
    #{url = "$BASE_URL/behandlung", name = "Behandlung"},
    #{url = "", name = "Behandlung", submenu = [{url = "$BASE_URL/behandlung/vorgehen/", name = "Meine Vorgehensweise"},{url = "$BASE_URL/behandlung/behandlungsmethoden/", name = "Behandlungsmethoden"},{url = "$BASE_URL/behandlung/preise/", name = "Preisübersicht"}]},
    {url = "$BASE_URL/behandlung/vorgehen/", name = "Meine Vorgehensweise"},
    {url = "$BASE_URL/behandlung/behandlungsmethoden/", name = "Behandlungsmethoden"},
    #{url = "$BASE_URL/behandlung/preise/", name = "Preisübersicht"},
    {url = "$BASE_URL/pages/blog/", name = "Blog"},
    {url = "$BASE_URL/about/", name = "Über mich"},   
    {url = "$BASE_URL/contact/", name = "Kontakt"}
]

clean_blog_social = [
    {url = "https://www.instagram.com/jessican_natuerlich/", icon="fab fa-instagram"},
    {url = "https://facebook.com/tierheilpraxisjessican", icon="fab fa-facebook"},
    {url = "https://twitter.com/thp_jessican", icon="fab fa-twitter"}
]
