# The URL the site will be built for
base_url = "https://tierheilpraxis-jessican.de/"
generate_rss = true
compile_sass = true

title = "Tierheilpraxis JessICan - natürlich gesund!"
description = "Entdecken Sie bei Tierheilpraktiker JessICan spezialisierte Therapieverfahren für Hunde und Pferde, einschließlich Akupunktur, Homöopathie, Phytotherapie, Manuelle Therapie, Arbeit mit ätherischen Ölen und Ernährungsberatung. Fördern Sie das Wohlbefinden Ihrer geliebten Vierbeiner und stärken Sie Ihre harmonische Beziehung."
highlight_code = false

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Jessi von JessICan"
clean_blog_menu = [
    #{url = "$BASE_URL", name = "Start"},
    #{url = "$BASE_URL/behandlung", name = "Behandlung"},
    {url = "", name = "Behandlung", submenu = [{url = "$BASE_URL/behandlung/vorgehen", name = "Meine Vorgehensweise"},{url = "$BASE_URL/behandlung/behandlungsmethoden", name = "Behandlungsmethoden"},{url = "$BASE_URL/behandlung/preise", name = "Preisübersicht"}]},
    {url = "$BASE_URL/pages/blog", name = "Blog"},
    {url = "$BASE_URL/about", name = "Über mich"},   
    {url = "$BASE_URL/contact", name = "Kontakt"}
]

clean_blog_social = [
    #{url = "https://www.instagram.com/jess.i.can_natuerlich/", icon="fab fa-instagram"}
]
